from typing import Iterator, List, Union, Any, Dict

class DemTarget:
    """Type stub for stim.DemTarget"""
    @property
    def val(self) -> int: ...
    def is_relative_detector_id(self) -> bool: ...

class DemInstruction:
    """Type stub for stim.DemInstruction"""
    @property
    def type(self) -> str: ...
    def targets_copy(self) -> List[DemTarget]: ...

class DetectorErrorModel:
    """Type stub for stim.DetectorErrorModel"""
    def flattened(self) -> Iterator[DemInstruction]: ...

class CompiledMeasurementSampler:
    """Type stub for sampler objects"""
    def sample(self, shots: int, bit_packed: bool = False, separate_observables: bool = False) -> Any: ...

class CircuitInstruction:
    """Type stub for stim.CircuitInstruction"""
    @property
    def name(self) -> str: ...
    def targets_copy(self) -> List[Any]: ...
    def gate_args_copy(self) -> List[float]: ...

class Circuit:
    """Type stub for stim.Circuit"""
    def __init__(self, stim_program_text: str = ""): ...
    
    # 1. 속성 (Properties)
    @property
    def num_qubits(self) -> int: ...
    @property
    def num_detectors(self) -> int: ...

    # 2. 메서드 (Methods)
    def compile_sampler(self) -> CompiledMeasurementSampler: ...
    def compile_detector_sampler(self) -> CompiledMeasurementSampler: ...
    
    def detector_error_model(self, decompose_errors: bool = False, flatten_loops: bool = False, ignore_decomposition_failures: bool = False) -> DetectorErrorModel: ...
    def get_detector_coordinates(self, only: Union[List[int], None] = None) -> Dict[int, List[float]]: ...
    
    # [핵심] 이번에 문제가 된 flattened와 append 추가
    def flattened(self) -> 'Circuit': ...
    def append(self, name: Union[str, CircuitInstruction], targets: Any = None, arg: Any = None) -> None: ...
    def copy(self) -> 'Circuit': ...
    
    # 반복문(for instruction in circuit)을 위한 Iterator 정의
    def __iter__(self) -> Iterator[CircuitInstruction]: ...

    @staticmethod
    def generated(
        code_task: str,
        distance: int,
        rounds: int,
        after_clifford_depolarization: float = 0,
        after_reset_flip_probability: float = 0,
        before_measure_flip_probability: float = 0,
        before_round_data_depolarization: float = 0
    ) -> 'Circuit': ...